# fly.toml app configuration file generated for sdmx-mcp-eval on 2026-03-27T15:30:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sdmx-mcp-eval'
primary_region = 'fra'

[build]

[env]
  SDMX_BASE_URL = 'https://sdmx.data.unicef.org/ws/public/sdmxapi/rest'
  SDMX_THEME_PREFIX_CSV = 'theme_prefixes_domain.csv'
  SDMX_QUERY_DIMENSION_POLICY_FILE = 'query_dimension_policy.json'
  SDMX_DISCOVERY_POLICY_FILE = 'discovery_policy.json'
  SDMX_DEFAULT_LAST_N_OBSERVATIONS = 'true'
  SDMX_EXCLUDE_DRAFT = 'true'
  SDMX_AGENCY_ALLOWLIST = 'UNICEF,UNPD'
  SDMX_REF_AREA_HIERARCHY_REF = 'UNICEF/UNICEF_REPORTING_REGIONS/latest'

[deploy]
  [deploy.release_command_vm]
    memory = '2048mb'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2048mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
